# Generated by Django 5.2 on 2025-04-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskqueue", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aitask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("syllabus_generation", "Syllabus Generation"),
                    ("lesson_content", "Lesson Content Generation"),
                    ("lesson_interaction", "Lesson Interaction"),
                    ("onboarding_assessment", "Onboarding Assessment"),
                    ("process_quiz_interaction", "Process Quiz Interaction"),
                ],
                max_length=50,
            ),
        ),
    ]
