# Generated by Django 5.2 on 2025-04-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="duration",
            field=models.IntegerField(
                blank=True,
                help_text="Estimated duration of the lesson in minutes.",
                null=True,
            ),
        ),
    ]
