# Generated by Django 5.2 on 2025-04-06 21:09

from django.db import migrations
from core.constants import DIFFICULTY_BEGINNER, DIFFICULTY_EARLY_LEARNER, DIFFICULTY_GOOD_KNOWLEDGE, DIFFICULTY_ADVANCED

def update_difficulty_levels(apps, schema_editor):
    """
    Update existing syllabi to use the standardized difficulty levels.
    Maps old levels to new ones based on case-insensitive matching.
    """
    Syllabus = apps.get_model('core', 'Syllabus')

    # Define mapping from old levels (lowercase) to new standardized levels
    level_mapping = {
        'beginner': DIFFICULTY_BEGINNER,
        'early learner': DIFFICULTY_EARLY_LEARNER,
        'good knowledge': DIFFICULTY_GOOD_KNOWLEDGE,
        'advanced': DIFFICULTY_ADVANCED,
        # Add any other variations that might exist in the database
        'intermediate': DIFFICULTY_GOOD_KNOWLEDGE,
        'expert': DIFFICULTY_ADVANCED,
        'basic': DIFFICULTY_BEGINNER,
        'novice': DIFFICULTY_BEGINNER,
    }

    # Update all syllabi
    for syllabus in Syllabus.objects.all():
        old_level = syllabus.level.lower() if syllabus.level else ''
        if old_level in level_mapping:
            syllabus.level = level_mapping[old_level]
            syllabus.save()
        else:
            # Default to beginner if level doesn't match any known value
            syllabus.level = DIFFICULTY_BEGINNER
            syllabus.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_lesson_duration'),  # Correct previous migration
    ]

    operations = [
        migrations.RunPython(update_difficulty_levels),
    ]
