# Generated by Django 5.2 on 2025-04-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_update_difficulty_levels"),
    ]

    operations = [
        migrations.AddField(
            model_name="syllabus",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("GENERATING", "Generating"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                db_index=True,
                default="PENDING",
                help_text="The generation status of the syllabus.",
                max_length=20,
                verbose_name="generation status",
            ),
        ),
        migrations.AlterField(
            model_name="syllabus",
            name="level",
            field=models.CharField(
                choices=[
                    ("Beginner", "Beginner"),
                    ("Early Learner", "Early Learner"),
                    ("Good Knowledge", "Good Knowledge"),
                    ("Advanced", "Advanced"),
                ],
                default="Beginner",
                help_text="The target knowledge level (e.g., beginner, advanced).",
                max_length=50,
            ),
        ),
    ]
