# Generated by Django 5.2 on 2025-04-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_syllabus_status_alter_syllabus_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessoncontent",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("GENERATING", "Generating"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                db_index=True,
                default="PENDING",
                help_text="The generation status of the lesson content.",
                max_length=20,
                verbose_name="generation status",
            ),
        ),
    ]
