# Generated by Django 5.2 on 2025-04-18 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_lessoncontent_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprogress",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="userprogress",
            name="core_userpr_user_id_8db698_idx",
        ),
        migrations.RemoveIndex(
            model_name="userprogress",
            name="core_userpr_syllabu_4a85db_idx",
        ),
        migrations.RemoveIndex(
            model_name="userprogress",
            name="core_userpr_user_id_0efd36_idx",
        ),
        migrations.RemoveIndex(
            model_name="userprogress",
            name="core_userpr_lesson__44d521_idx",
        ),
        migrations.AlterUniqueTogether(
            name="userprogress",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="userprogress",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="userprogress",
            name="lesson_state_json",
        ),
        migrations.RemoveField(
            model_name="userprogress",
            name="score",
        ),
        migrations.RemoveField(
            model_name="userprogress",
            name="updated_at",
        ),
    ]
