# Generated by Django 5.2 on 2025-04-18 16:13

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_userprogress_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprogress",
            options={
                "verbose_name": "User Progress",
                "verbose_name_plural": "User Progress Records",
            },
        ),
        migrations.AddField(
            model_name="module",
            name="duration",
            field=models.IntegerField(
                blank=True,
                help_text="Estimated duration of the lesson in minutes.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Timestamp when the progress record was first created.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprogress",
            name="lesson_completed",
            field=models.BooleanField(
                default=False, help_text="Indicates if the lesson has been completed."
            ),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="lesson_state_json",
            field=models.JSONField(
                blank=True,
                help_text="JSON blob storing conversational state or other lesson-specific data.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="score",
            field=models.FloatField(
                blank=True,
                help_text="Score achieved by the user for this lesson, if applicable.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp when the progress record was last updated.",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userprogress",
            unique_together={("user", "syllabus", "module_index", "lesson_index")},
        ),
        migrations.AddIndex(
            model_name="userprogress",
            index=models.Index(fields=["user"], name="core_userpr_user_id_8db698_idx"),
        ),
        migrations.AddIndex(
            model_name="userprogress",
            index=models.Index(
                fields=["syllabus"], name="core_userpr_syllabu_4a85db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprogress",
            index=models.Index(
                fields=["user", "syllabus"], name="core_userpr_user_id_0efd36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprogress",
            index=models.Index(
                fields=["lesson"], name="core_userpr_lesson__44d521_idx"
            ),
        ),
    ]
