# Generated by Django 5.2 on 2025-04-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_userprogress_options_module_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprogress",
            name="lesson_state_json",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON blob storing conversational state or other lesson-specific data.",
                null=True,
            ),
        ),
    ]
